//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wqwz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormData
    {
        public int Id { get; set; }
        public int PostUserId { get; set; }
        public System.DateTime Date { get; set; }
        public int FormFieldId { get; set; }
    
        public virtual User User { get; set; }
        public virtual FormField FormField { get; set; }
    }
}
