//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wqwz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.FormFields = new HashSet<FormField>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public bool Pass { get; set; }
        public string Content { get; set; }
        public int UserId { get; set; }
        public int FormTypeId { get; set; }
    
        public virtual User ReleaseUser { get; set; }
        public virtual FormType FormType { get; set; }
        public virtual ICollection<FormField> FormFields { get; set; }
    }
}
