//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wqwz.Models
{
    using System;
    
    public enum FormFieldType : int
    {
        Text = 0,
        Date = 1,
        Number = 2,
        Regex = 3,
        TextArea = 4,
        EnumRadio = 5,
        EnumCheck = 6,
        EnumSelect = 7
    }
}
