//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wqwz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.NewsType = new HashSet<NewsType>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int ReleaseUserId { get; set; }
        public bool Pass { get; set; }
        public int Type { get; set; }
        public string Content { get; set; }
    
        public virtual ICollection<NewsType> NewsType { get; set; }
        public virtual User User { get; set; }
    }
}
