//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wqwz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Forms = new HashSet<Form>();
            this.News = new HashSet<News>();
            this.FormDatas = new HashSet<FormData>();
        }
    
        public int Id { get; set; }
        public UserType Type { get; set; }
        public string Name { get; set; }
        public string Pwd { get; set; }
        public SexType Sex { get; set; }
        public System.DateTime RegDate { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Form> Forms { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<FormData> FormDatas { get; set; }
    }
}
