//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wqwz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wqwzContainer : DbContext
    {
        public wqwzContainer()
            : base("name=wqwzContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<News> NewsSet { get; set; }
        public virtual DbSet<NewsType> NewsTypeSet { get; set; }
        public virtual DbSet<Form> FormSet { get; set; }
        public virtual DbSet<FormType> FormTypeSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<FormField> FormFieldSet { get; set; }
        public virtual DbSet<FormData> FormDataSet { get; set; }
        public virtual DbSet<FormFieldEnum> FormFieldEnumSet { get; set; }
    }
}
